server:
  port: 8090
  servlet:
    context-path: /datos_medicos/api

spring:
  application:
    name: DatosMedicos
  datasource:
    url: jdbc:postgresql://localhost:5432/datos_medicos_db
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method